# Generated by Django 6.0.6 on 2026-06-22 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignoffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('sync_retries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('site_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BomDetail',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bom_detail', serialize=False, to='core.signoffdocument')),
                ('site_code', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=50)),
                ('high_risk', models.BooleanField(default=False)),
                ('cost_impact_high', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferDetail',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transfer_detail', serialize=False, to='core.signoffdocument')),
                ('source_site', models.CharField(max_length=10)),
                ('target_site', models.CharField(max_length=10)),
                ('from_warehouse', models.CharField(max_length=50)),
                ('to_warehouse', models.CharField(max_length=50)),
                ('material_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('urgent', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BomItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('material_status', models.CharField(max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='core.signoffdocument')),
            ],
        ),
        migrations.AddField(
            model_name='signoffdocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_created', to='core.user'),
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acting_as', to='core.user')),
                ('delegator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_to', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('site_code', models.CharField(max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('delegated_from', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='core.signoffdocument')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_steps', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='core.signoffdocument')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_logs', to='core.user')),
            ],
        ),
    ]
