# Generated by Django 6.0.6 on 2026-06-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signoffdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
