# Generated by Django 4.2.30 on 2026-06-30 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='員工代號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(max_length=50, verbose_name='職位')),
                ('site_code', models.CharField(max_length=10, verbose_name='所屬廠區')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SignoffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BOM', '物料清單 (BOM)'), ('MATERIAL_TRANSFER', '物料轉移 (Material Transfer)')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交 (系統檢查中)'), ('APPROVING', '簽核中'), ('APPROVED', '簽核核准'), ('REJECTED', '已駁回'), ('CLOSED', '已結案 (外部同步成功)'), ('CANCELED', '已撤銷'), ('SYNC_FAILED', '外部同步失敗')], default='DRAFT', max_length=20)),
                ('version', models.IntegerField(default=1, verbose_name='樂觀鎖版本號')),
                ('sync_retries', models.IntegerField(default=0, verbose_name='外部同步重試次數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signoff_documents',
            },
        ),
        migrations.CreateModel(
            name='BomDetail',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bom_detail', serialize=False, to='signoff.signoffdocument')),
                ('site_code', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=50)),
                ('high_risk', models.BooleanField(default=False)),
                ('cost_impact_high', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'bom_details',
            },
        ),
        migrations.CreateModel(
            name='TransferDetail',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transfer_detail', serialize=False, to='signoff.signoffdocument')),
                ('source_site', models.CharField(max_length=10)),
                ('target_site', models.CharField(max_length=10)),
                ('from_warehouse', models.CharField(max_length=50)),
                ('to_warehouse', models.CharField(max_length=50)),
                ('material_id', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('urgent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'transfer_details',
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='代理生效起始時間')),
                ('end_at', models.DateTimeField(verbose_name='代理生效結束時間')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='代理人')),
                ('delegator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_given', to=settings.AUTH_USER_MODEL, verbose_name='被代理的主管')),
            ],
            options={
                'db_table': 'delegations',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='關卡順序')),
                ('role', models.CharField(max_length=50, verbose_name='所需角色')),
                ('site_code', models.CharField(max_length=10, verbose_name='所需廠區')),
                ('status', models.CharField(choices=[('PENDING', '待簽核'), ('APPROVED', '已同意'), ('REJECTED', '已駁回')], default='PENDING', max_length=20)),
                ('delegated_from', models.CharField(blank=True, max_length=50, null=True, verbose_name='原被代理主管 ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='審核意見')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_approved', to=settings.AUTH_USER_MODEL, verbose_name='實際簽核人')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='signoff.signoffdocument')),
            ],
            options={
                'db_table': 'approval_steps',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', '提交'), ('APPROVE', '核准'), ('REJECT', '駁回'), ('CANCEL', '撤回'), ('REVISE', '修改重提'), ('RETRY_SYNC', '重試外部同步')], max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='signoff.signoffdocument')),
            ],
            options={
                'db_table': 'approval_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BomItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('material_status', models.CharField(choices=[('ACTIVE', '啟用中'), ('DISABLED', '已停用')], max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='signoff.bomdetail')),
            ],
            options={
                'db_table': 'bom_item_details',
            },
        ),
    ]
