# Generated by Django 4.2.30 on 2026-06-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('SUBMIT', '提交'), ('APPROVE', '核准'), ('REJECT', '駁回'), ('AUTO_REJECT', '系統自動駁回'), ('CANCEL', '撤回'), ('REVISE', '修改重提'), ('RETRY_SYNC', '重試外部同步'), ('CLOSE', '結案'), ('SLA_REMIND', 'SLA 催辦'), ('SYNC_FAILED', '外部同步失敗')], max_length=30),
        ),
    ]
